### ISSUE TITLE
Missing textures

### ISSUE THREAD

**Issue by CaptainBoggle** [Noahkiq/minecraft-randomiser#1]
Hey, thanks for making this firstly, it is truly amazing. So far on macOS I have only one problem, which is likely not OS related, and that is that sometimes textures will be replaced with the purple/black checkerboard pattern instead of another in game pattern. It would be great if you could eliminate this issue. Thanks!

**Comment by qixils** [comment]
i've been looking into this, some textures just aren't properly supported by different models and such, especially animated ones. properly fixing this would require a lot of manual removal of files so i might just add a toggle to disable animated textures entirely, which will make it slightly less random but a little less checkerboardy if people prefer.

**Comment by qixils** [comment]
oh, they changed the naming of animation detail files. does this new commit fix it?

**Comment by CaptainBoggle** [comment]
I will check now

**Comment by CaptainBoggle** [comment]
Yep, seems completely fixed. Thanks.
