### ISSUE TITLE
nothing randomises

### ISSUE THREAD

**Issue by popedaddy69** [Noahkiq/minecraft-randomiser#10]
I opened the resource_randomiser.py file and it installed but nothing randomised. Have I missed something?
I am also not sure where to write the commands such as `python3 resource_randomiser.py -h`.

**Comment by qixils** [comment]
you'd run the commands in your command prompt/powershell/terminal/etc, but they aren't needed as long as you have python installed.
did the resource pack successfully install to your resource packs folder? is there anything in it?

**Comment by popedaddy69** [comment]
there are things in the folder and it is in resourcepacks. 
![image](https://user-images.githubusercontent.com/56842558/67267843-0a3f0d00-f4ab-11e9-8316-65795e0d7194.png)
![image](https://user-images.githubusercontent.com/56842558/67267907-2b9ff900-f4ab-11e9-8297-c76a7a22b55b.png)
but nothing has randomises and i was hoping for sounds

**Comment by popedaddy69** [comment]
it turns out i just needed to extract shuffle but i am still not sure how to only randomise sounds

**Comment by qixils** [comment]
that's odd, not sure why you need to extract.
you could delete everything except the sound folder, or use the command prompt to run `python3 resource_randomiser.py --notextures --noblockstates --notexts --nofonts --noshaders`

**Comment by popedaddy69** [comment]
when i type the command it ends up as 
![image](https://user-images.githubusercontent.com/56842558/67400589-c250e080-f5a5-11e9-888d-95e08acb6fb0.png)

**Comment by qixils** [comment]
ah, the windows command may be "python" or "python3.8" (probably, unless it was installed a while ago, then "python3.7" maybe..) -- if neither work then python might not be installed to the PATH which is outside of my ability to help, but google could assist with that...

**Comment by popedaddy69** [comment]
I have got python in the PATH, but now it says this.
![image](https://user-images.githubusercontent.com/56842558/67558945-db75a080-f70f-11e9-91d6-05b5b57e3fa8.png)
What does this mean?
My pack folder have these
![image](https://user-images.githubusercontent.com/56842558/67559021-0102aa00-f710-11e9-9b9f-946e671859e8.png)

**Comment by popedaddy69** [comment]
So it turns out i put the randomiser inside of avaliable instead of selected ooof
