### ISSUE TITLE
Both randomizers use forward slashes, which don't work on Windows

### ISSUE THREAD

**Issue by vitalline** [Noahkiq/minecraft-randomiser#4]
Paths on Windows use backward slashes, not forward ones. This results in the resource randomizer working only partially and the data randomizer not working at all.

**Comment by Alluseri** [comment]
Windows is not picky on slashes. I don't know about Windows 10(not an autist, sorry), but in Windows 7 it is so.

**Comment by vitalline** [comment]
Well, I just checked. Under Windows 10, the randomizer doesn't recognize paths with forward slashes in them and, as a result, simply treats the folders as empty.
Here is a "result" of me running the Datapack Randomizer on Win10 without any commandline arguments. (I tested it by changing the slashes to escaped backslashes, and it worked just fine.)
[random_data.zip](https://github.com/noellekiq/minecraft-randomiser/files/3638333/random_data.zip)

**Comment by qixils** [comment]
working on a patch rn

**Comment by qixils** [comment]
Hopefully fixed by https://github.com/noellekiq/minecraft-randomiser/commit/b44dc7ad879fd9d0ff30249d41ad1a502c891614 and https://github.com/noellekiq/minecraft-randomiser/commit/f4d1966cf82249a03ea744b4049272e4d695f9cb, if it's still broke then something else is wrong
