### ISSUE TITLE
Text processing works under local codepage when it should use UTF-8

### ISSUE THREAD

**Issue by vitalline** [Noahkiq/minecraft-randomiser#5]
After opening UTF-8 translation files in local codepage (which in my case is `cp65001`), `readlines()` crashes when working with UTF-8. The same thing happens when writing UTF-8 using `write()` into a file opened in local codepage.
This can be fixed by adding `encoding='utf-8'` to the `open()` functions (particularly on lines 196, 225 and 236 of `resource_randomiser.py`).

**Comment by qixils** [comment]
that should hopefully fix it, though this weirdly didn't show up in any of my testing (even my basic tests on windows)

**Comment by vitalline** [comment]
Yeah, that's just about what I did when trying to get it to work. It's probably a locale-specific problem, given that I use the Russian locale and encounter problems because of it relatively frequently.
