### ISSUE TITLE
Separate Items, Blocks and Non-Cube Blocks in texture randomizing (maybe make it optional)

### ISSUE THREAD

**Issue by MatiHW** [Noahkiq/minecraft-randomiser#8]
The first shuffled pack I got was grass = Lily pads, and tree leaves = boat item texture. I think this ruins the point of a random texture pack for me... I want things like dirt -> quarts block and endstone -> obsidian... or polished andesite... not lily pads and item textures...

Maybe if you really wanted to, you could make it the default but add an option to disable it, but I don't think that's necessary.

**Comment by qixils** [comment]
`--alttextures` does this, pretty much
